export const products = [
    { id: 1, category: 'CATEGORY', name: 'The Catalyzer', price: '$16.00', imageUrl: "https://rukminim2.flixcart.com/image/832/832/xif0q/gown/u/f/w/na-s-full-sleeve-stitched-sss-203-femvy-na-original-imah2gg366ytzq7d.jpeg?q=70&crop=false" },
    { id: 2, category: 'CATEGORY', name: 'Shooting Stars', price: '$21.15', imageUrl: 'https://rukminim2.flixcart.com/image/832/832/xif0q/gown/u/f/w/na-s-full-sleeve-stitched-sss-203-femvy-na-original-imah2gg366ytzq7d.jpeg?q=70&crop=false' },
    { id: 3, category: 'CATEGORY', name: 'Neptune', price: '$12.00', imageUrl: 'https://rukminim2.flixcart.com/image/832/832/xif0q/gown/u/f/w/na-s-full-sleeve-stitched-sss-203-femvy-na-original-imah2gg366ytzq7d.jpeg?q=70&crop=false' },
    { id: 4, category: 'CATEGORY', name: 'The 400 Blows', price: '$18.40', imageUrl: 'https://rukminim2.flixcart.com/image/832/832/xif0q/gown/u/f/w/na-s-full-sleeve-stitched-sss-203-femvy-na-original-imah2gg366ytzq7d.jpeg?q=70&crop=false' },
    { id: 5, category: 'CATEGORY', name: 'The Catalyzer', price: '$16.00', imageUrl: 'https://rukminim2.flixcart.com/image/832/832/xif0q/gown/u/f/w/na-s-full-sleeve-stitched-sss-203-femvy-na-original-imah2gg366ytzq7d.jpeg?q=70&crop=false' },
    { id: 6, category: 'CATEGORY', name: 'Shooting Stars', price: '$21.15', imageUrl: 'https://rukminim2.flixcart.com/image/832/832/xif0q/gown/u/f/w/na-s-full-sleeve-stitched-sss-203-femvy-na-original-imah2gg366ytzq7d.jpeg?q=70&crop=false' },
    { id: 7, category: 'CATEGORY', name: 'Neptune', price: '$12.00', imageUrl: 'https://rukminim2.flixcart.com/image/832/832/xif0q/gown/u/f/w/na-s-full-sleeve-stitched-sss-203-femvy-na-original-imah2gg366ytzq7d.jpeg?q=70&crop=false' },
    { id: 8, category: 'CATEGORY', name: 'The 400 Blows', price: '$18.40', imageUrl: 'https://rukminim2.flixcart.com/image/832/832/xif0q/gown/u/f/w/na-s-full-sleeve-stitched-sss-203-femvy-na-original-imah2gg366ytzq7d.jpeg?q=70&crop=false' },
  ];